version: 19
jobs:
- name: express ci
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !SetBuildVersionStep
    name: set build version
    buildVersion: '@script:builtin:node:determine-project-version@'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: build & test
    runInContainer: true
    image: node:10.16-alpine
    interpreter: !DefaultInterpreter
      commands:
      - npm install
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: build docker
    runInContainer: true
    image: ubuntu:latest
    interpreter: !DefaultInterpreter
      commands:
      - docker build -t merilairon.com:5000/@project_name@:@script:builtin:node:determine-project-version@
        -t merilairon.com:5000/@project_name@:latest .
      - docker push merilairon.com:5000/@project_name@:latest
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  caches:
  - key: npm-cache
    path: /root/.npm
  timeout: 3600
